name: okteto
on:
  schedule:
    - cron: 10 22 * * *
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install wget
        sudo apt-get -y install curl
    - name: Clone source
      run: |
        cd /home/runner
        wget https://github.com/okteto/okteto/releases/download/1.8.9/okteto-Linux-x86_64
        chmod +x ./okteto-Linux-x86_64
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
        wget https://github.com/byxiaopeng/okteto-reboot/raw/master/v2tls.yml
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
    - name: go kaishi
      run: |
        /home/runner/okteto-Linux-x86_64 login --token ${{ secrets.APITOKEN }}
        #okteto的api密钥
        /home/runner/okteto-Linux-x86_64 namespace ${{ secrets.namespace }}
        #Namespace用户名
        #xx.yml  
        kubectl replace --force -f /home/runner/v2tls.yml    
        #kubectl replace 强制覆盖项目 
    - uses: actions/upload-artifact@master
      with:
        name: result
        path: /home/runner/2tls.yml
